### ISSUE TITLE
Add our values and explain the vision for this group

### ISSUE THREAD

**Issue by moul** [francep2p/p2p.paris#11]
* Autonomous -> managed by the community
* Nonprofit
* Framework for other meetups
...

**Comment by alexsland** [comment]
need text for content

**Comment by moul** [comment]
@gorhgorh @zooma2k18: can you start a draft for this? :)

**Comment by gorhgorh** [comment]
sure, I'm out tonight but I'll start tomorrow

**Comment by moul** [comment]
values are available here: https://github.com/parisp2p/community/tree/master/docs
