### ISSUE TITLE
Redirect to /fr for french users is broken

### ISSUE THREAD

**Issue by alexsland** [francep2p/p2p.paris#29]

**Comment by moul** [comment]
what's the current behavior? redirecting to /en?

**Comment by moul** [comment]
that's because the file _redirects is at the root of the repo, it should instead be placed somewhere so when hugo builds the website, the file is at the root like a favicon.ico or robots.txt

**Comment by moul** [comment]
@alexsland 	still broken?

**Comment by cdeleeuwe** [comment]
It seems that when sending multiple languages in the "Accept-Language" header, Netlify always returns the default language.

Some tests:
```bash
$ curl https://deploy-preview-75--p2pparis.netlify.com
Redirecting to /en/
```
```bash
$ curl -H 'accept-language: fr' https://deploy-preview-75--p2pparis.netlify.com
Redirecting to /fr/
```
```bash
$ curl -H 'accept-language: fr,en' https://deploy-preview-75--p2pparis.netlify.com
Redirecting to /en/
```

Anyway, I have already contact Netlify support about it, and they are currently checking.

**Comment by cdeleeuwe** [comment]
Netlify support came back.. their reply:
"it is a bug which we may not get a fix for soon.  I'll update you via email in case things do change though!". 

So I think for now there is not much we can do about it.
