### ISSUE TITLE
Configure Netlify to auto build the website everyday even without push

### ISSUE THREAD

**Issue by moul** [francep2p/p2p.paris#62]
In order to get the event status updated automatically

**Comment by cdeleeuwe** [comment]
We can trigger a build with a simple curl call to Netlify's build hook URL. So we just need a cronjob to do this.

Came accross this post https://community.netlify.com/t/scheduling-builds-and-deploys-with-netlify/2563/9, which uses GitHub actions. Nice thing about using GitHub Actions is that it lets us to keep this cronjob configuration within the repo.

@moul , let me know I should give it a try?
