### ISSUE TITLE
Animated logo

### ISSUE THREAD

**Issue by moul** [francep2p/p2p.paris#7]

**Comment by moul** [comment]
First attempt, adding directly in the SVG file:

```html
    <style>
      polygon, path, polyline {
        stroke-dasharray: 100;
        animation: dash 5s linear infinite;
      }
      #Shape-Copy {
        stroke-dasharray: none;
        animation: none !important;
      }

      @keyframes dash {
        to {
          stroke-dashoffset: 1000;
        }
      }
    </style>
```

https://codepen.io/moul/pen/orOqBv?editors=1000

**Comment by moul** [comment]
New versions:

* https://codepen.io/moul/full/ZEzBvgW
* https://codepen.io/moul/full/zYOoRON

**Comment by gorhgorh** [comment]
I has just like "But ... how does he do that with css", then i saw lottie )

**Comment by gorhgorh** [comment]
reaveal animation of the first one is really cool, also lottie looks really great

**Comment by moul** [comment]
done in #57
